# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: (Commit) Format Python Code

on:
    push:
        paths:
            - '**.py'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Black
      run: |
        isort .
        black .

    - name: Commit and Push Changes
      run: |
        git config user.name 'Github Actions'
        git config --local user.email "action@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Format Python Code"
        git push 


