# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: (Commit) Format Python Code

on:
    push:
        paths:
            - '**.py'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run
      run: |
        isort .
        black .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Auto Code Format
        title: Fixes by format action
        body: This is an auto-generated PR with fixes.
        labels: automated pr
        branch: automated-python-code-format

