

name: Format Python Code
on: push
jobs:
  python-code-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Display Python version
        run: python --version
      - name: Install packages
        run: pip install black isort autopep8
      - name: Formatter
        run: |
          black .
          autopep8 --recursive --in-place --aggressive --aggressive .
          isort .
      - name: commit format changes
        run: |
          git config --global --add safe.directory /github/workspace
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git diff-index --cached --quiet HEAD || git commit -m ' Auto Code Format'
          
      - name: push isort changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     commit-message: Auto Code Format
      #     title: Fixes by format action
      #     body: This is an auto-generated PR with fixes.
      #     labels: automated pr
      #     branch: python-code-format-patches
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Display Python version
        run: python --version
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Pytest
        run: pytest

